version: '3.8'

services:
  jupyter:
    build: .
    container_name: diabetes-xgboost
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
